### ISSUE TITLE
Consider MIT license

### ISSUE THREAD

**Issue by rich-j** [CillianMyles/tap-canvas#22]
This looks like a useful package - however, we can't consider using it because it is GPL licensed. [The GPL license is tainting:](https://stackoverflow.com/a/6923255/8696915)

> Which means the package as a whole gets the limitations of the GPL. As that is more restrictive you can no longer use it in commercial (or rather closed source) software. Which also means if you have a MIT/BSD/ASL project you will not want to add dependencies to GPL code.

Consider changing the license to an MIT license. The GPL taint is the reason that most packages published on [pub.dev](pub.dev) are MIT licensed. Good luck.

**Comment by CillianMyles** [comment]
Hi @rich-j 👋 

Good news: version 0.9.5 is now MIT. 

Bad news: I have also deprecated the package as the framework added a better way to do this. 

More information here: https://github.com/flutter/flutter/pull/107262

**Comment by rich-j** [comment]
@CillianMyles - a big **triple "Thanks"!**  👍🏼 

1. Thanks for changing the license terms.
2. Thanks for the referral to the new Flutter `TapRegion` widget.
3. Thanks for helping the entire community both with this package and deprecating it when no longer needed.

💯
